name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.ya?ml"
      - "PopRockets/**"
      - "**.ino"
  pull_request:
    paths:
      - ".github/workflows/ci.ya?ml"
      - "PopRockets/**"
      - "**.ino"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - path: PopRockets
            project-type: sketch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: "arduino:samd:mkrwifi1010"
          libraries: |
            - name: Arduino_MKRENV
            - name: Arduino_MKRGPS
            - name: SD
            - name: OneWire
            - name: DallasTemperature

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          path: ${{ matrix.project.path }}
          project-type: ${{ matrix.project.project-type }}
          compliance: strict
