name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.ya?ml"
      - "RecorderAmbient/**"
      - "**.ino"
  pull_request:
    paths:
      - ".github/workflows/ci.ya?ml"
      - "RecorderAmbient/**"
      - "**.ino"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v2
        with:
          path: RecorderAmbient
          compliance: strict
